<% chef_versions = %w(12 13) %>
<% platforms     = { :ubuntu => %w(16.04 14.04), :centos => %w(7.2 6.8) } %>
---
driver:
  name: vagrant
  customize:
    nictype1: virtio

platforms:
<% platforms.each do |platform, platform_versions| %>
<%   platform_versions.each do |platform_version| %>
<%     chef_versions.each do |chef_version| %>
- name: <%= platform %>-<%= platform_version %>-chef-<%= chef_version %>
  driver:
    box: bento/<%= platform %>-<%= platform_version %>
  driver_config:
    require_chef_omnibus: <%= chef_version %>
  run_list:
    <% if platform == :ubuntu %>- recipe[apt]<% end %>
    <% if platform == :centos %>- recipe[apt]<% end %>
<%     end %>
<%   end %>
<% end %>

suites:
- name: default
  run_list:
  - recipe[poise-supervisor]
